### PR TITLE
Buckaroo All gateway

### PR DESCRIPTION
**Pull request by yasasn86**
buckaroo payments methods select page

### CODE REVIEW

**Comment by silvano-a** [comment]
Is this pull request complete? 
what does it do?

**Comment by yasasn86** [comment]
It helps to go to buckaroo payments methods select page, so that we can select any payment method supported by buckaroo there. 
we can use the gateway  `Buckaroo_All` to do that if you merged this code.
I don't know whether there is another way to do that currently.

**Comment by silvano-a** [comment]
there is, yes :)

it's called the 'PurchaseRequest'. 

usage: `$gateway = new BuckarooGateway(); `
`$gateway->purchase();`

**Comment by yasasn86** [comment]
ok. I was using omnipay with payum bundle.  here is my current configuration
        buckaroo_via_omnipay:
            factory: omnipay
            type: Buckaroo_All
            websiteKey: %buckaroo_website_key%
            secretKey: %buckaroo_secret_key%
            testMode: %test_mode%

I don't know which name should be used for type in this configuration as you suggest. If I use `Buckaroo` it does not work and throws an error. but if I use Buckaroo_All it works with this merged code.

**Comment by silvano-a** [comment]
Could you try replacing ` type: Buckaroo_All ` by ` type: Buckaroo_Gateway ` and post the results here? 
https://github.com/thephpleague/omnipay-buckaroo/issues/22

**Comment by yasasn86** [comment]
type: Buckaroo_Gateway
screenshot from 2016-09-26 16-53-48

**Comment by silvano-a** [comment]
My bad, try 
`type: Buckaroo`

**Comment by yasasn86** [comment]
ok. my previous sreenshot it for 
type: Buckaroo

**Comment by silvano-a** [comment]
i've created an issue for this. it seems that there is something going wrong in the 'BuckarooGateway' lets move the discussion over there
https://github.com/thephpleague/omnipay-buckaroo/issues/22

**Comment by yasasn86** [comment]
ok. I think if we change the class name of `BuckarooGateway`  to Gateway, it will fix the issue 
class BuckarooGateway extends AbstractGateway
{
    public function getName()
    {
        return 'Buckaroo Gateway';
    }
...
to
class Gateway extends AbstractGateway
{
    public function getName()
    {
        return 'Buckaroo';
    }
...

**Comment by silvano-a** [comment]
can you confirm if this works, and if so, create a pull request including unit test?

**Comment by yasasn86** [comment]
I just checked it and it worked with class name Gateway

class Gateway extends AbstractGateway
{
    public function getName()
    {
        return 'Buckaroo';
    }
....

**Comment by silvano-a** [comment]
nice!

Could you create a pull request that fixes this?

**Comment by yasasn86** [comment]
ok. I will create a pull request :)

**Comment by silvano-a** [comment]
awesome! 
then this PR can be closed as an issue is opened for it, and this PR is not the solution to the problem

**Pull request closed without merging**
